spring:
    application:
        name: game
    datasource:
        url: jdbc:postgresql://localhost:5432/bobworld
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                  dialect: org.hibernate.dialect.PostgreSQLDialect
    mvc:
        servlet:
            encoding:
                charset: UTF-8
                enabled: true
                force: true

    web:
        reactive:
            multipart:
                enabled: false

    mustache:
        servlet:
            expose-request-attributes: true

    logging:
        level:
            org:
                springframework:
                    security: DEBUG

git